// Native.swift split: this file is one domain slice of the `Native`
// seam (see Native.swift for the class, shared state, and installBindings).
// Persistence (UserDefaults) + clipboard (pasteboard).

import AppKit
import CLua

extension Native {
    // MARK: - Persistence (UserDefaults)

    func getSetting(_ L: OpaquePointer?) -> Int32 {
        guard let key = LuaState.string(L, 1) else { return luaError(L, "get_setting: key required") }
        let v = UserDefaults.standard.object(forKey: key)
        switch v {
        case let n as NSNumber:
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                lua_pushboolean(L, n.boolValue ? 1 : 0)
            } else {
                lua_pushnumber(L, n.doubleValue)
            }
        case let s as String:
            lua_pushstring(L, s)
        default:
            lua_pushnil(L)
        }
        return 1
    }

    func setSetting(_ L: OpaquePointer?) -> Int32 {
        guard let key = LuaState.string(L, 1) else { return luaError(L, "set_setting: key required") }
        let defaults = UserDefaults.standard
        switch lua_type(L, 2) {
        case LUA_TBOOLEAN: defaults.set(LuaState.bool(L, 2) ?? false, forKey: key)
        case LUA_TNUMBER:  defaults.set(LuaState.double(L, 2)!, forKey: key)
        case LUA_TSTRING:  defaults.set(LuaState.string(L, 2)!, forKey: key)
        case LUA_TNIL:     defaults.removeObject(forKey: key)
        default:
            return luaError(L, "set_setting: only bool/number/string/nil supported (key '\(key)')")
        }
        return 0
    }

    // MARK: - Clipboard

    func pasteboardRead(_ L: OpaquePointer?) -> Int32 {
        if let s = NSPasteboard.general.string(forType: .string) {
            lua_pushstring(L, s)
        } else {
            lua_pushnil(L)
        }
        return 1
    }

    func pasteboardWrite(_ L: OpaquePointer?) -> Int32 {
        guard let s = LuaState.string(L, 1) else { return luaError(L, "pasteboard_write: string required") }
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(s, forType: .string)
        return 0
    }

    // The pasteboard types clipboard managers must not record -- password
    // managers mark secrets Concealed; expansion utilities mark ephemera
    // Transient (the nspasteboard.org convention, donor ClipboardTool's list).
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    // pasteboard_info() -> { change = <changeCount>, concealed = bool }.
    // Lets a history poller detect changes WITHOUT reading the contents, and
    // skip entries the source marked as secrets.
    func pasteboardInfo(_ L: OpaquePointer?) -> Int32 {
        let pb = NSPasteboard.general
        let concealed = pb.types?.contains { Native.concealedTypes.contains($0.rawValue) } ?? false
        lua_createtable(L, 0, 2)
        lua_pushinteger(L, lua_Integer(pb.changeCount)); lua_setfield(L, -2, "change")
        lua_pushboolean(L, concealed ? 1 : 0);           lua_setfield(L, -2, "concealed")
        return 1
    }
}
