#!/usr/bin/env python3
"""Generate README's feature catalog from the features themselves.

The catalog used to be hand-written, and it rotted exactly as you'd expect: it
went stale, and never once named window_deck -- the most actively developed
feature in the repo. A list maintained by hand restates a fact the code already
owns, so it drifts by construction.

Every feature self-describes in `app/features/<id>/feature.json` (name,
description, category) -- the SAME file the Settings UI renders from, so a wrong
description here is a wrong description in the app, and gets fixed for a real
reason. This reads those and rewrites the block between the FEATURES markers in
README.md.

    scripts/gen-readme-features.py            # rewrite the block
    scripts/gen-readme-features.py --check    # exit 1 if stale (CI runs this)

Discovery matches the APP's: it globs `<id>/lua/init.lua` (what
`registry.discover` keys off), NOT `<id>/feature.json`. Globbing the json would
let a feature ship with no feature.json, be absent from the catalog, and still
pass --check -- reintroducing the very bug this guards against. A feature without
a feature.json is an ERROR here: it cannot be documented, so it must not be
silently dropped.

The grouping is the app's OWN category taxonomy -- the same one Settings renders.
If a group reads badly, fix the `category` in feature.json; Settings and the
README improve together. Don't add a prettier mapping here: that would just be a
second thing to keep in sync.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- FEATURES:BEGIN (generated by scripts/gen-readme-features.py -- do not edit by hand) -->"
END = "<!-- FEATURES:END -->"

# Presentation order + heading per category. A category absent here still renders
# (under its raw name), so a new one can never be silently dropped.
GROUPS = [
    ("productivity", "Productivity"),
    ("health", "Health"),
    ("appearance", "Appearance"),
    ("platform", "Platform"),
]


def die(msg):
    sys.exit(f"gen-readme-features: {msg}")


def clean(value, field, feature_id):
    """Collapse whitespace and refuse anything that would corrupt the block.

    A raw newline in a description would inject arbitrary markdown into the
    bullet list; a literal HTML-comment marker would duplicate the END marker
    and leave the file in a state no re-run can converge out of.
    """
    text = " ".join(str(value).split())
    if not text:
        die(f"{feature_id}: feature.json is missing a non-empty '{field}'")
    if "<!--" in text or "-->" in text:
        die(f"{feature_id}: '{field}' contains an HTML comment marker, which would corrupt README")
    return text


def load_features():
    inits = sorted(ROOT.glob("app/features/*/lua/init.lua"))
    if not inits:
        die("found no features under app/features/*/lua/init.lua -- wrong working directory?")

    out = []
    for init in inits:
        fdir = init.parent.parent
        fj = fdir / "feature.json"
        if not fj.exists():
            die(f"{fdir.name}: has lua/init.lua but no feature.json, so it cannot be documented")
        try:
            d = json.loads(fj.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            die(f"{fj.relative_to(ROOT)}: invalid JSON -- {e}")

        out.append(
            {
                "name": clean(d.get("name", ""), "name", fdir.name),
                "description": clean(d.get("description", ""), "description", fdir.name),
                "category": clean(d.get("category", "general"), "category", fdir.name),
            }
        )
    return out


def render(features):
    by_cat = {}
    for f in features:
        by_cat.setdefault(f["category"], []).append(f)

    known = {c for c, _ in GROUPS}
    ordered = GROUPS + [(c, c.title()) for c in sorted(by_cat) if c not in known]

    n = len(features)
    lines = [BEGIN, ""]
    lines.append(
        f"**{n} feature{'s' if n != 1 else ''}**, each off by default, "
        "switched on in Settings and bindable to any trigger."
    )
    lines.append("")
    for cat, heading in ordered:
        items = by_cat.get(cat)
        if not items:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        for f in sorted(items, key=lambda x: x["name"]):
            lines.append(f"- **{f['name']}** -- {f['description']}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")

    if text.count(BEGIN) != 1 or text.count(END) != 1:
        die(
            f"README.md must contain exactly one FEATURES:BEGIN and one FEATURES:END marker "
            f"(found {text.count(BEGIN)} and {text.count(END)})"
        )
    if text.index(BEGIN) > text.index(END):
        die("README.md has FEATURES:END before FEATURES:BEGIN")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + render(load_features()) + tail

    if "--check" in sys.argv:
        if new != text:
            sys.exit(
                "README's feature catalog is out of date.\n"
                "A feature was added, renamed, or re-described and the README never caught up.\n"
                "Run: scripts/gen-readme-features.py"
            )
        print("README feature catalog is in sync.")
        return

    # Write via a temp file + atomic replace, so an interrupted run can't leave a
    # half-written README behind.
    tmp = readme.with_suffix(".md.tmp")
    tmp.write_text(new, encoding="utf-8")
    tmp.replace(readme)
    print("README feature catalog regenerated.")


if __name__ == "__main__":
    main()
