#!/usr/bin/env python3
"""Generate the feature catalog -- README's and the download page's -- from the
features themselves.

The catalog used to be hand-written, and it rotted exactly as you'd expect: it
went stale, and never once named window_deck -- the most actively developed
feature in the repo. A list maintained by hand restates a fact the code already
owns, so it drifts by construction.

Every feature self-describes in `app/features/<id>/feature.json` (name,
description, category) -- the SAME file the Settings UI renders from, so a wrong
description here is a wrong description in the app, and gets fixed for a real
reason. This reads those and rewrites the block between the FEATURES markers in
README.md and in site/index.html. Both render from the same parsed list, so the
page cannot advertise a roster the README (and the app) does not have.

    scripts/gen-readme-features.py            # rewrite both blocks
    scripts/gen-readme-features.py --check    # exit 1 if either is stale (CI runs this)

Discovery matches the APP's: it globs `<id>/lua/init.lua` (what
`registry.discover` keys off), NOT `<id>/feature.json`. Globbing the json would
let a feature ship with no feature.json, be absent from the catalog, and still
pass --check -- reintroducing the very bug this guards against. A feature without
a feature.json is an ERROR here: it cannot be documented, so it must not be
silently dropped.

Each feature also self-declares what it may REACH (`capabilities` in the same
file, enforced at runtime by the Lua capability gate). That is surfaced here for
the reader who has not cloned anything: the catalog is the first place a stranger
sees what these features can do to their machine, and "most of them reach nothing"
is only credible if the few that DO are named in the same list.

The grouping is the app's OWN category taxonomy -- the same one Settings renders.
If a group reads badly, fix the `category` in feature.json; Settings and the
README improve together. Don't add a prettier mapping here: that would just be a
second thing to keep in sync.
"""

import html
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def markers(block):
    """The BEGIN/END comment pair delimiting one generated block."""
    return (
        f"<!-- {block}:BEGIN (generated by scripts/gen-readme-features.py -- do not edit by hand) -->",
        f"<!-- {block}:END -->",
    )


BEGIN, END = markers("FEATURES")
PERMS_BEGIN, PERMS_END = markers("PERMISSIONS")

# Presentation order + heading per category. A category absent here still renders
# (under its raw name), so a new one can never be silently dropped. Mirrors
# CATEGORY_ORDER + categoryLabel in FeatureChrome.swift, so the README sections
# and the Settings sidebar read in the same order with the same names;
# manifest.KNOWN_CATEGORIES is the vocabulary's enforcement point.
# The section order, and the ONLY input to it. Must stay identical to
# CATEGORY_ORDER (FeatureChrome.swift), which carries the reasoning and which
# testCategoryVocabularyIsConsistent holds this list to -- as a SEQUENCE, not a
# set, so the README and the Settings sidebar cannot print the same eight names
# in two different orders.
GROUPS = [
    ("windows", "Windows"),
    ("visibility", "Visibility & Trust"),
    ("switching", "Switching & Search"),
    ("text", "Text"),
    ("health", "Health"),
    ("utilities", "Utilities"),
    ("appearance", "Appearance"),
    ("general", "General"),
]


# Reader-facing wording per capability, and the order they are listed in
# (by reach, not alphabetically). Must list every capability in
# manifest.CAPABILITY_METHODS, in the order sortedCapabilities (FeatureChrome.swift)
# shows them -- testEveryCapabilityHasHostPresentation holds this list to both,
# as a SEQUENCE. An unknown capability still renders, under its raw name: showing
# LESS reach than a feature actually has is the one thing this must never do.
CAPABILITY_ORDER = ["input", "browser", "network", "files", "apps", "power", "commands", "exec"]
CAPABILITY_WORDS = {
    "input": "types keystrokes",
    "browser": "reads browser tabs",
    "network": "network",
    "files": "reads/writes files",
    "apps": "sees installed apps",
    "power": "sleep/lock",
    "commands": "runs other features",
    "exec": "runs other programs",
}

# What each OS precondition a feature `requires` is called, and what it covers.
# A precondition missing here is an error rather than a raw-id bullet: the
# permissions list is the reader's answer to "what will this ask me for?".
REQUIRES_WORDS = {
    "accessibility": (
        "Accessibility",
        "to read or move windows, act on the current selection, or press keys on your behalf",
    ),
}


def die(msg):
    sys.exit(f"gen-readme-features: {msg}")


def capability_note(caps, feature_id):
    """The parenthetical reach note, or "" when the feature declares nothing.

    Silence means "reaches nothing", which is the common case (most features
    touch only windows and panels) and is the informative half of this: a reader
    scanning the list should be able to see at a glance that the annotated ones
    are the exception.
    """
    if not caps:
        return ""
    if not isinstance(caps, list) or any(not isinstance(c, str) for c in caps):
        die(f"{feature_id}: 'capabilities' must be a list of strings")
    rank = {c: i for i, c in enumerate(CAPABILITY_ORDER)}
    ordered = sorted(caps, key=lambda c: (rank.get(c, 99), c))
    return ", ".join(CAPABILITY_WORDS.get(c, c) for c in ordered)


def clean(value, field, feature_id):
    """Collapse whitespace and refuse anything that would corrupt the block.

    A raw newline in a description would inject arbitrary markdown into the
    bullet list; a literal HTML-comment marker would duplicate the END marker
    and leave the file in a state no re-run can converge out of.
    """
    text = " ".join(str(value).split())
    if not text:
        die(f"{feature_id}: feature.json is missing a non-empty '{field}'")
    if "<!--" in text or "-->" in text:
        die(f"{feature_id}: '{field}' contains an HTML comment marker, which would corrupt README")
    if "{{" in text:
        die(f"{feature_id}: '{field}' contains '{{{{', which the download page reads as a template token")
    return text


def load_features():
    inits = sorted(ROOT.glob("app/features/*/lua/init.lua"))
    if not inits:
        die("found no features under app/features/*/lua/init.lua -- wrong working directory?")

    out = []
    for init in inits:
        fdir = init.parent.parent
        fj = fdir / "feature.json"
        if not fj.exists():
            die(f"{fdir.name}: has lua/init.lua but no feature.json, so it cannot be documented")
        try:
            d = json.loads(fj.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            die(f"{fj.relative_to(ROOT)}: invalid JSON -- {e}")

        order = d.get("order")
        if order is not None and not isinstance(order, int):
            die(f"{fdir.name}: order must be an integer, got {order!r}")

        out.append(
            {
                "name": clean(d.get("name", ""), "name", fdir.name),
                "description": clean(d.get("description", ""), "description", fdir.name),
                "category": clean(d.get("category", "general"), "category", fdir.name),
                "capabilities": capability_note(d.get("capabilities", []), fdir.name),
                "browser": "browser" in (d.get("capabilities") or []),
                "requires": d.get("requires") or [],
                # Ships enabled on a fresh install. The lead line below states
                # the real default rather than asserting a blanket "all off",
                # which was false the moment the first defaultEnabled landed.
                "default_enabled": d.get("defaultEnabled") is True,
                # Slot within the category section; None sorts last, alphabetically.
                "order": order,
            }
        )
    return out


# The lead sentence, shared by both renderers. One fixed sentence plus a per-row
# marker, NOT a sentence assembled from who currently carries the flag. A
# generated claim about the roster ("every feature in X", "as are the trust
# features") is an identity claim that no count can guard, so it goes false the
# moment the curation moves and --check still passes -- it regenerates the same
# wrong sentence. The marker is also strictly more informative: a reader sees
# WHICH rows are on instead of inferring it from a section-level claim.
#
# No count in it -- the strategy memo's copy rule ("never lead with the feature
# count") applies to generated copy too; a number here also goes stale as the
# catalog moves.
LEAD = (
    "A feature ships {off} unless its row says {on} -- those work from a fresh "
    "install. Switch on whatever else you want in Settings and bind it to any trigger."
)


def sections(features):
    """(heading, [feature, ...]) per non-empty category, both levels in shipped order.

    The one place order is decided, so the README and the page cannot list the
    same features in two different orders.
    """
    by_cat = {}
    for f in features:
        by_cat.setdefault(f["category"], []).append(f)

    known = {c for c, _ in GROUPS}
    ordered = GROUPS + [(c, c.title()) for c in sorted(by_cat) if c not in known]

    out = []
    for cat, heading in ordered:
        items = by_cat.get(cat)
        if not items:
            continue
        # Two features in one section claiming the same slot means the tie breaks
        # alphabetically and the declared order silently isn't the order shipped --
        # exactly the quiet kind of wrong this whole ordering exists to remove. Die
        # instead; CI runs --check, so it cannot ship unnoticed.
        ranks = [f["order"] for f in items if f["order"] is not None]
        dupes = sorted({r for r in ranks if ranks.count(r) > 1})
        if dupes:
            clash = ", ".join(
                f"order={r}: " + " + ".join(sorted(f["name"] for f in items if f["order"] == r))
                for r in dupes
            )
            die(f"category '{cat}' has features sharing an order -- {clash}")

        # Ranked features first in declared order, then the unranked ones by name.
        # SettingsView.featuresIn sorts by the same two keys.
        items = sorted(items, key=lambda x: (x["order"] is None, x["order"] or 0, x["name"]))
        out.append((heading, items))
    return out


def render_markdown(features):
    lines = [BEGIN, ""]
    lines.append(LEAD.format(off="**off**", on="*on by default*"))
    lines.append("")
    for heading, items in sections(features):
        lines.append(f"### {heading}")
        lines.append("")
        for f in items:
            reach = f" <sub>Reaches: {f['capabilities']}.</sub>" if f["capabilities"] else ""
            on = " *(on by default)*" if f["default_enabled"] else ""
            lines.append(f"- **{f['name']}**{on} -- {f['description']}{reach}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def prose_html(text):
    """Escape feature.json prose for HTML, and set its ` -- ` as the dash it means."""
    return html.escape(text, quote=False).replace(" -- ", " &mdash; ")


def render_html(features):
    """The same catalog as the README, as the download page's markup.

    Indented to sit inside the page's catalog <section>; the classes it emits
    (.lead, .cats, .cat, .feats, .feat, .on, .reach) are styled by site/index.html.
    """
    pad = "    "
    lines = [BEGIN]
    # Escape the template BEFORE formatting, so the markup it gains is not escaped.
    lead = prose_html(LEAD).format(off="<strong>off</strong>", on="<em>on by default</em>")
    lines.append(f'{pad}<p class="lead">{lead}</p>')
    lines.append(f'{pad}<div class="cats">')
    for heading, items in sections(features):
        lines.append(f'{pad}<div class="cat">')
        lines.append(f"{pad}  <h3>{html.escape(heading)}</h3>")
        lines.append(f'{pad}  <ul class="feats">')
        for f in items:
            on = ' <span class="on">on by default</span>' if f["default_enabled"] else ""
            reach = (
                f'<span class="reach">Reaches: {html.escape(f["capabilities"])}.</span>'
                if f["capabilities"] else ""
            )
            lines.append(
                f'{pad}    <li class="feat"><strong>{html.escape(f["name"])}</strong>{on}'
                f'<p>{prose_html(f["description"])}</p>{reach}</li>'
            )
        lines.append(f"{pad}  </ul>")
        lines.append(f"{pad}</div>")
    lines.append(f"{pad}</div>")
    lines.append(f"{pad}{END}")
    return "\n".join(lines)


def permissions(features):
    """(label, what it covers, [feature names]) per OS permission, catalog order.

    Accessibility comes from each feature's declared `requires`; Automation from
    the `browser` capability, since every browser read drives Chrome/Safari over
    AppleScript. A hand-kept list of names here went stale the way the catalog
    did, so neither is kept by hand. Scope is FEATURES: a rules-engine effect
    that scripts another app (setAppearance drives System Events) prompts too,
    and is not listed here.
    """
    ordered = [f for _, items in sections(features) for f in items]
    out = []
    for req, (label, covers) in REQUIRES_WORDS.items():
        names = [f["name"] for f in ordered if req in f["requires"]]
        if names:
            out.append((label, covers, names))
    unknown = sorted({r for f in ordered for r in f["requires"]} - set(REQUIRES_WORDS))
    if unknown:
        die(f"no REQUIRES_WORDS entry for required permission(s): {', '.join(unknown)}")
    browser = [f["name"] for f in ordered if f["browser"]]
    if browser:
        out.append((
            "Automation",
            "features that read browser tabs drive Chrome and Safari through "
            "AppleScript, so macOS prompts once per browser",
            browser,
        ))
    return out


def render_permissions_markdown(features):
    lines = [PERMS_BEGIN, ""]
    for label, covers, names in permissions(features):
        lines.append(f"- **{label}** -- {covers}: {', '.join(names)}.")
    lines += ["", PERMS_END]
    return "\n".join(lines)


def render_permissions_html(features):
    pad = "    "
    lines = [PERMS_BEGIN, f'{pad}<ul class="perms">']
    for label, covers, names in permissions(features):
        lines.append(
            f"{pad}  <li><strong>{html.escape(label)}</strong> &mdash; "
            f"{prose_html(covers)}: {html.escape(', '.join(names))}.</li>"
        )
    lines += [f"{pad}</ul>", f"{pad}{PERMS_END}"]
    return "\n".join(lines)


# Every generated block: the file, its markers, and the renderer. All are checked
# by --check, so none can drift from another or from the features.
TARGETS = [
    ("README.md", BEGIN, END, render_markdown),
    ("site/index.html", BEGIN, END, render_html),
    ("README.md", PERMS_BEGIN, PERMS_END, render_permissions_markdown),
    ("site/index.html", PERMS_BEGIN, PERMS_END, render_permissions_html),
]


def splice(name, text, begin, end, rendered):
    """`text` with the block between `begin` and `end` replaced by `rendered`."""
    if text.count(begin) != 1 or text.count(end) != 1:
        die(
            f"{name} must contain exactly one {begin} and one {end} marker "
            f"(found {text.count(begin)} and {text.count(end)})"
        )
    if text.index(begin) > text.index(end):
        die(f"{name} has {end} before {begin}")

    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return head + rendered + tail


def main():
    if set(CAPABILITY_WORDS) != set(CAPABILITY_ORDER):
        die("CAPABILITY_WORDS and CAPABILITY_ORDER list different capabilities")
    features = load_features()
    check = "--check" in sys.argv

    # Splice every block of a file before comparing or writing it once.
    originals, updated = {}, {}
    for rel, begin, end, render in TARGETS:
        if rel not in updated:
            originals[rel] = updated[rel] = (ROOT / rel).read_text(encoding="utf-8")
        updated[rel] = splice(rel, updated[rel], begin, end, render(features))
    stale = [rel for rel in updated if updated[rel] != originals[rel]]

    if check:
        if stale:
            sys.exit(
                f"The feature catalog is out of date in: {', '.join(stale)}.\n"
                "A feature was added, renamed, or re-described and the docs never caught up.\n"
                "Run: scripts/gen-readme-features.py"
            )
        print(f"Feature catalog is in sync ({', '.join(updated)}).")
        return

    for rel in stale:
        # Write via a temp file + atomic replace, so an interrupted run can't
        # leave a half-written file behind.
        path = ROOT / rel
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(updated[rel], encoding="utf-8")
        tmp.replace(path)
    print(f"Feature catalog regenerated: {', '.join(stale) or 'nothing changed'}.")


if __name__ == "__main__":
    main()
