#!/usr/bin/env python3
"""Generate README's feature catalog from the features themselves.

The catalog used to be hand-written, and it rotted exactly as you'd expect: it
went stale, and never once named window_deck -- the most actively developed
feature in the repo. A list maintained by hand restates a fact the code already
owns, so it drifts by construction.

Every feature self-describes in `app/features/<id>/feature.json` (name,
description, category) -- the SAME file the Settings UI renders from, so a wrong
description here is a wrong description in the app, and gets fixed for a real
reason. This reads those and rewrites the block between the FEATURES markers in
README.md.

    scripts/gen-readme-features.py            # rewrite the block
    scripts/gen-readme-features.py --check    # exit 1 if stale (CI runs this)

Discovery matches the APP's: it globs `<id>/lua/init.lua` (what
`registry.discover` keys off), NOT `<id>/feature.json`. Globbing the json would
let a feature ship with no feature.json, be absent from the catalog, and still
pass --check -- reintroducing the very bug this guards against. A feature without
a feature.json is an ERROR here: it cannot be documented, so it must not be
silently dropped.

Each feature also self-declares what it may REACH (`capabilities` in the same
file, enforced at runtime by the Lua capability gate). That is surfaced here for
the reader who has not cloned anything: the catalog is the first place a stranger
sees what these features can do to their machine, and "most of them reach nothing"
is only credible if the few that DO are named in the same list.

The grouping is the app's OWN category taxonomy -- the same one Settings renders.
If a group reads badly, fix the `category` in feature.json; Settings and the
README improve together. Don't add a prettier mapping here: that would just be a
second thing to keep in sync.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- FEATURES:BEGIN (generated by scripts/gen-readme-features.py -- do not edit by hand) -->"
END = "<!-- FEATURES:END -->"

# Presentation order + heading per category. A category absent here still renders
# (under its raw name), so a new one can never be silently dropped. Mirrors
# CATEGORY_ORDER + categoryLabel in FeatureChrome.swift, so the README sections
# and the Settings sidebar read in the same order with the same names;
# manifest.KNOWN_CATEGORIES is the vocabulary's enforcement point.
GROUPS = [
    ("windows", "Windows"),
    ("switching", "Switching & Search"),
    ("text", "Text"),
    ("health", "Health"),
    ("utilities", "Utilities"),
    ("visibility", "Visibility & Trust"),
    ("appearance", "Appearance"),
    ("general", "General"),
]


# Reader-facing wording per capability, and the order they are listed in
# (by reach, not alphabetically -- same ranking the Settings UI uses).
# Mirrors manifest.CAPABILITY_METHODS, which is the enforcement source of truth.
# An unknown capability still renders, under its raw name: showing LESS reach
# than a feature actually has is the one thing this must never do.
CAPABILITY_ORDER = ["input", "browser", "network", "files", "power", "commands"]
CAPABILITY_WORDS = {
    "input": "types keystrokes",
    "browser": "reads browser tabs",
    "network": "network",
    "files": "reads/writes files",
    "power": "sleep/lock",
    "commands": "runs other features",
}


def die(msg):
    sys.exit(f"gen-readme-features: {msg}")


def capability_note(caps, feature_id):
    """The parenthetical reach note, or "" when the feature declares nothing.

    Silence means "reaches nothing", which is the common case (most features
    touch only windows and panels) and is the informative half of this: a reader
    scanning the list should be able to see at a glance that the annotated ones
    are the exception.
    """
    if not caps:
        return ""
    if not isinstance(caps, list) or any(not isinstance(c, str) for c in caps):
        die(f"{feature_id}: 'capabilities' must be a list of strings")
    rank = {c: i for i, c in enumerate(CAPABILITY_ORDER)}
    ordered = sorted(caps, key=lambda c: (rank.get(c, 99), c))
    return ", ".join(CAPABILITY_WORDS.get(c, c) for c in ordered)


def clean(value, field, feature_id):
    """Collapse whitespace and refuse anything that would corrupt the block.

    A raw newline in a description would inject arbitrary markdown into the
    bullet list; a literal HTML-comment marker would duplicate the END marker
    and leave the file in a state no re-run can converge out of.
    """
    text = " ".join(str(value).split())
    if not text:
        die(f"{feature_id}: feature.json is missing a non-empty '{field}'")
    if "<!--" in text or "-->" in text:
        die(f"{feature_id}: '{field}' contains an HTML comment marker, which would corrupt README")
    return text


def load_features():
    inits = sorted(ROOT.glob("app/features/*/lua/init.lua"))
    if not inits:
        die("found no features under app/features/*/lua/init.lua -- wrong working directory?")

    out = []
    for init in inits:
        fdir = init.parent.parent
        fj = fdir / "feature.json"
        if not fj.exists():
            die(f"{fdir.name}: has lua/init.lua but no feature.json, so it cannot be documented")
        try:
            d = json.loads(fj.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            die(f"{fj.relative_to(ROOT)}: invalid JSON -- {e}")

        order = d.get("order")
        if order is not None and not isinstance(order, int):
            die(f"{fdir.name}: order must be an integer, got {order!r}")

        out.append(
            {
                "name": clean(d.get("name", ""), "name", fdir.name),
                "description": clean(d.get("description", ""), "description", fdir.name),
                "category": clean(d.get("category", "general"), "category", fdir.name),
                "capabilities": capability_note(d.get("capabilities", []), fdir.name),
                # Slot within the category section; None sorts last, alphabetically.
                "order": order,
            }
        )
    return out


def render(features):
    by_cat = {}
    for f in features:
        by_cat.setdefault(f["category"], []).append(f)

    known = {c for c, _ in GROUPS}
    ordered = GROUPS + [(c, c.title()) for c in sorted(by_cat) if c not in known]

    # No count in the lead line -- the strategy memo's copy rule ("never lead
    # with the feature count") applies to this generated block too; a number
    # here also goes stale as the catalog moves.
    lines = [BEGIN, ""]
    lines.append(
        "Every feature ships **off by default** -- switch one on in Settings "
        "and bind it to any trigger."
    )
    lines.append("")
    for cat, heading in ordered:
        items = by_cat.get(cat)
        if not items:
            continue
        # Two features in one section claiming the same slot means the tie breaks
        # alphabetically and the declared order silently isn't the order shipped --
        # exactly the quiet kind of wrong this whole ordering exists to remove. Die
        # instead; CI runs --check, so it cannot ship unnoticed.
        ranks = [f["order"] for f in items if f["order"] is not None]
        dupes = sorted({r for r in ranks if ranks.count(r) > 1})
        if dupes:
            clash = ", ".join(
                f"order={r}: " + " + ".join(sorted(f["name"] for f in items if f["order"] == r))
                for r in dupes
            )
            die(f"category '{cat}' has features sharing an order -- {clash}")

        lines.append(f"### {heading}")
        lines.append("")
        # Ranked features first in declared order, then the unranked ones by name.
        # SettingsView.featuresIn sorts by the same two keys.
        for f in sorted(items, key=lambda x: (x["order"] is None, x["order"] or 0, x["name"])):
            reach = f" <sub>Reaches: {f['capabilities']}.</sub>" if f["capabilities"] else ""
            lines.append(f"- **{f['name']}** -- {f['description']}{reach}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")

    if text.count(BEGIN) != 1 or text.count(END) != 1:
        die(
            f"README.md must contain exactly one FEATURES:BEGIN and one FEATURES:END marker "
            f"(found {text.count(BEGIN)} and {text.count(END)})"
        )
    if text.index(BEGIN) > text.index(END):
        die("README.md has FEATURES:END before FEATURES:BEGIN")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + render(load_features()) + tail

    if "--check" in sys.argv:
        if new != text:
            sys.exit(
                "README's feature catalog is out of date.\n"
                "A feature was added, renamed, or re-described and the README never caught up.\n"
                "Run: scripts/gen-readme-features.py"
            )
        print("README feature catalog is in sync.")
        return

    # Write via a temp file + atomic replace, so an interrupted run can't leave a
    # half-written README behind.
    tmp = readme.with_suffix(".md.tmp")
    tmp.write_text(new, encoding="utf-8")
    tmp.replace(readme)
    print("README feature catalog regenerated.")


if __name__ == "__main__":
    main()
